server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel-app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; 
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}

# server {
#     listen 80;                          # Configura o servidor para ouvir na porta 80 (HTTP padrão)
#     server_name localhost;              # Define o nome do servidor (neste caso, localhost)

#     root /var/www/html/public;          # Define o diretório raiz do servidor (pasta "public" do Laravel)
#     index index.php index.html index.htm; # Especifica os arquivos padrão para carregamento no diretório raiz

#     location / {                        # Bloco para a rota principal
#         try_files $uri $uri/ /index.php?$query_string;
#                                          # Tenta carregar o arquivo solicitado, a pasta, ou redireciona para index.php
#     }

#     location ~ \.php$ {                 # Bloco para processar arquivos PHP
#         fastcgi_pass laravel-app:9000;  # Redireciona para o PHP-FPM no container chamado "laravel-app" na porta 9000
#         fastcgi_index index.php;        # Define o arquivo padrão para execução via PHP-FPM
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#                                          # Define o caminho completo do script PHP
#         include fastcgi_params;         # Inclui os parâmetros padrão para FastCGI
#     }

#     location ~ /\.ht {                  # Bloco para bloquear o acesso a arquivos ".ht*"
#         deny all;                       # Nega o acesso a esses arquivos
#     }
# }
